### PR TITLE
Textbox

### PR DESCRIPTION
**Pull request by Jarod42**

### CODE REVIEW

**Review by midwan — APPROVED** [review]

**Comment by midwan** [comment]
Hmm, this actually started breaking Amiberry, so I can to roll it back.
Not sure where exactly the problem occurs, but it segfaults as soon as it starts.

**Comment by Jarod42** [comment]
:-/
From what I (quickly) see from (future) Guichan commits, `Text::SetRow` is broken/unimplemented. Text Field had a visual issue.
I don't see a crash fix.

I quickly tested with demo provided and no crashes.
I will review the code to see if I see a problem.
Investigating...

**Comment by Jarod42** [comment]
@midwan : I have found the issue and fix :-)
It is `TextField::GetText` which return dangling reference.
Guichan's fix happens in 2 PRs :-)

**Review by midwan — APPROVED** [review]

**Comment by midwan** [comment]
Hm, I'm still getting a segfault on startup in Amiberry, even after merging all the latest commits from guisan here. Unless you didn't apply all the fixes yet, there must be something more... I'll see if I have time to dig through it in more detail.

**Comment by Jarod42** [comment]
> Guichan's fix happens in 2 PRs :-)

So it is un-merged https://github.com/Jarod42/guisan/tree/textfield_fix
(in particular
[include/guisan/widgets/textfield.hpp](https://github.com/kallisti5/guisan/compare/master...Jarod42:guisan:textfield_fix#diff-d97bd1cf61cb8a5235c199159bde73373b92fc80da3bba1ad64e0e7eb3dfe315)
```diff
-        const std::string& getText() const;
+        std::string getText() const;
```

)
(just after https://github.com/Jarod42/guisan/tree/empty_rectangle)

**Comment by midwan** [comment]
@Jarod42 I tried that, along with the related change in `textfield.cpp`, but it doesn't make a difference. It still segfauls on startup for me.

**Comment by midwan** [comment]
Putting a few breakpoints in the code, I found where the crash happens:

It starts off here:
```
void TextField::setText(const std::string& text)
{
    mText->setRow(0, text);
}
```
which takes us to `text.cpp` here:
```
    void Text::setRow(unsigned int row, const std::string& content)
    {
        if (row >= mRows.size()) throw GCN_EXCEPTION("Row out of bounds!");
    }
```
And I get a `Row out of bounds` exception eventually.

**Comment by midwan** [comment]
It seems to be, that instead of `setRow` it should be calling `setContext`. So, I changed it to that, and got further.
The application started up, but I eventually got another segfault, when opening one of the GUI panels.

The crash happened again in `text.cpp`, specifically here:

```
    Rectangle Text::getCaretDimension(Font* font) const
    {
        Rectangle dim;
        dim.x = font->getWidth(mRows[mCaretRow].substr(0, mCaretColumn));
        dim.y = font->getHeight() * mCaretRow;
        dim.width = font->getWidth(" ");
        // We add two for some extra spacing to be sure the whole caret is visible.
        dim.height = font->getHeight() + 2;
        return dim;
    }
```

and more specifically, in this line: `dim.x = font->getWidth(mRows[mCaretRow].substr(0, mCaretColumn));`

The callstack was this:
```
 	libstdc++.so.6!std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const	
>	gcn::Text::getCaretDimension(const gcn::Text * const this, gcn::Font * font) Line 334	C++
 	gcn::TextField::draw(gcn::TextField * const this, gcn::Graphics * graphics) Line 144	C++
 	gcn::BasicContainer::drawChildren(gcn::BasicContainer * const this, gcn::Graphics * graphics) Line 336	C++
 	gcn::Container::draw(gcn::Container * const this, gcn::Graphics * graphics) Line 86	C++
 	gcn::BasicContainer::drawChildren(gcn::BasicContainer * const this, gcn::Graphics * graphics) Line 336	C++
 	gcn::Container::draw(gcn::Container * const this, gcn::Graphics * graphics) Line 86	C++
 	gcn::Gui::draw(gcn::Gui * const this) Line 198	C++
 	check_input() Line 828	C++
 	amiberry_gui_run() Line 868	C++
 	run_gui() Line 1252	C++
 	gui_init() Line 449	C++
 	real_main2(int argc, TCHAR ** argv) Line 1467	C++
 	real_main(int argc, TCHAR ** argv) Line 1563	C++
 	main(int argc, char ** argv) Line 4409	C++
```

Looks like `text.cpp` needs some more fixes first?

**Comment by Jarod42** [comment]
Thanks for investigation, I will see how/when guichan fixes that.

**Pull request merged**
