### PR TITLE
Apply guichan's change 8565f3e8ce86c771551dadc2d91cf883d7f9d917 (dec 22th 2007)

### PR DESCRIPTION
**Pull request by Jarod42**
- Documentation has been enhanced.
- The alignment `enum` in `Graphics`, the orientation `enum` in `Slider` and the scroll policy `enum` in `ScrollArea` are no longer anonymous enums.
- Locale variable names have in some places been changed to better reflect their purpose.
- move some methods from `public` to `protected`.

### CODE REVIEW

**Comment by kallisti5** [comment]
@Jarod42 I'm inviting you as a collaborator to this repository.   I've fell behind maintaining it, and it looks like a few people want to work on it as of Dec  2023.  The outstanding patches are large enough, I don't have the bandwidth to review all of them.

**Comment by kallisti5** [comment]
@midwan  FYI about the above.   I'll rope you in as a collaborator as well.  My only ask is to do a bit of code review of each other since y'all have some long pull requests outstanding :-)

**Comment by midwan** [comment]
@kallisti5 
Thanks!
I was planning on coming back to my PR, now that the summer break is closing in. So I think I'll split it up as suggested and re-submit it in a more clean way. :)

**Comment by kallisti5** [comment]
Yup!  Sorry for letting these sit for so long.  It's been a busy year, and my project time has been shorter than usual.

**Comment by Jarod42** [comment]
Just waiting for review (to do or to receive ;-) )

**Review by midwan — APPROVED** [review]
Looks good to me

**Pull request merged**
